<div id="item_table">
  <?= $this->recoms ?>
  <div class="item_table_row template">
    <div class="item_table_cell template">
      <div class="title"></div>
      <div class="img"></div>
      <div class="rep">
        <input class="rep_input" maxlength="1" />
      </div>
    </div>
  </div>
</div>

<button id="sendBtn">送信</button>

<h1>Import Item Data</h1>
<button id="importButton">IMPORT</button>
<div id="importRes"></div>

<?php

$this->inlineScript()->appendScript(
<<<__END__

function log(_){ console.log.apply(console, arguments); }
function post(_opt){
  var url = _opt["url"],
      type = _opt["type"],
      query = _opt["query"],
      callback = _opt["callback"];
  $.ajax({
    "type": type,
    "url": url,
    "data": JSON.stringify(query),
    "contentType": "application/json",
    "dataType": "json",
    "success": function(_data){ callback(true, _data); },
    "error": function(_data){ callback(false, {"statusCode": _data["status"], "response": _data["responseText"]}); }
  });
}

$("#button01").on("click", function(){
  $("#a1").text($("#a1").text() + "a");
  log("a");
  var id = 1
      query = {"text": "testest"};
  // post({
  //   "url": "http://localhost/app/test",
  //   "type": "get",
  //   "query": query,
  //   "callback": function(_result, _data){
  //     log(_result, _data);
  //     if(!_result){ $("#a1").html(_data["response"]); }
  //   }
  // });

  post({
    "url": "http://localhost/app/test",
    "type": "post",
    "query": query,
    "callback": function(_result, _data){
      log(_result, _data);
      if(!_result){ $("#a1").html(_data["response"]); }
    }
  });
});

var isImporting = false;
$("#importButton").on("click", function(){
  if(isImporting) { return; }
  isImporting = true;
  var importFunc = (function(_i){
    if(_i > 261){ return; }
    post({
      "url": "http://localhost/app/item/import_" + _i,
      "type": "get",
      "callback": function(_result, _data){
        log(_result, _data);
        if(_result){
          $("#importRes").append($("<div>"+_data['data']+"</div>"));
        }
        importFunc(_i+1);
      }
    });
  });
  importFunc(1);
});

__END__
);
